/*
# AquaTrak — Complete Database Schema

## Overview
Full schema for AquaTrak, a lean SMB operations platform for water tank cleaning businesses.
Single-tenant design: one merchant operates the system. All data is accessible to the
anon-key client (no auth UI in scope).

## New Tables
1. **merchants** — Business owner profile
2. **staff** — Employee records with daily wage
3. **customers** — Customer records with tank details and location
4. **service_cards** — Service job tracking with status lifecycle
5. **attendance** — Staff check-in/check-out with geofence verification
6. **inventory** — Chemical supply stock levels with minimum thresholds
7. **inventory_transactions** — Audit log for every stock deduction
8. **service_inventory_requirements** — Per-service-type chemical usage rates per 1000L
9. **stock_alerts** — Low-stock notifications generated by trigger
10. **cron_logs** — Execution log for the daily reminder cron job
11. **support_tickets** — AI FAQ and human escalation ticket tracking

## Triggers
- **auto_deduct_inventory**: After service_cards.job_status changes to 'completed',
  automatically deducts inventory based on tank capacity x per-1000L requirement rates,
  and creates stock_alerts if stock falls below threshold.

## Security
- RLS enabled on every table.
- All tables use `TO anon, authenticated` with `USING (true)` - single-tenant app,
  no sign-in required, data is intentionally shared within the business.

## Seed Data
- 1 sample merchant (Sunil Sharma, AquaClean Services)
- 2 staff members
- 3 sample customers with varying tank sizes
- 3 service cards (1 pending, 1 in_progress, 1 completed)
- 2 inventory items (Chlorine 500g, Bleaching Powder 2000g)
- Service inventory requirements for standard_cleaning service type
*/

-- ============================================================
-- ENUMS
-- ============================================================
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_status') THEN
    CREATE TYPE job_status AS ENUM ('pending', 'in_progress', 'completed');
  END IF;
END $$;

-- ============================================================
-- TABLES (order matters for FK dependencies)
-- ============================================================

CREATE TABLE IF NOT EXISTS merchants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_name text NOT NULL,
  owner_name text NOT NULL,
  phone text NOT NULL,
  email text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS staff (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id uuid NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text NOT NULL,
  daily_wage_inr integer NOT NULL DEFAULT 500,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id uuid NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text NOT NULL,
  address text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  tank_capacity_liters integer NOT NULL DEFAULT 1000,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS service_cards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  merchant_id uuid NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  service_type text NOT NULL DEFAULT 'standard_cleaning',
  quantity integer,
  service_date date NOT NULL DEFAULT current_date,
  next_service_date date,
  job_status job_status NOT NULL DEFAULT 'pending',
  technician_id uuid REFERENCES staff(id),
  notes text,
  reminder_sent_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  merchant_id uuid NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  checkin_time timestamptz,
  checkout_time timestamptz,
  verified_location boolean NOT NULL DEFAULT false,
  date date NOT NULL DEFAULT current_date,
  notes text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id uuid NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  item_name text NOT NULL,
  unit text NOT NULL DEFAULT 'g',
  current_stock numeric(10,2) NOT NULL DEFAULT 0,
  minimum_threshold numeric(10,2) NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  inventory_id uuid NOT NULL REFERENCES inventory(id) ON DELETE CASCADE,
  service_card_id uuid NOT NULL REFERENCES service_cards(id) ON DELETE CASCADE,
  quantity_deducted numeric(10,2) NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS service_inventory_requirements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  service_type text NOT NULL,
  item_name text NOT NULL,
  quantity_per_1000L numeric(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  inventory_id uuid NOT NULL REFERENCES inventory(id) ON DELETE CASCADE,
  merchant_id uuid NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  alert_type text NOT NULL DEFAULT 'low_stock',
  resolved boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cron_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL,
  status text NOT NULL,
  error_message text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS support_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_phone text NOT NULL,
  message text NOT NULL,
  ai_response text,
  requires_human_intervention boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'open',
  created_at timestamptz DEFAULT now()
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_customers_merchant ON customers(merchant_id);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_service_cards_merchant ON service_cards(merchant_id);
CREATE INDEX IF NOT EXISTS idx_service_cards_status ON service_cards(job_status);
CREATE INDEX IF NOT EXISTS idx_service_cards_next_service ON service_cards(next_service_date);
CREATE INDEX IF NOT EXISTS idx_staff_merchant ON staff(merchant_id);
CREATE INDEX IF NOT EXISTS idx_staff_phone ON staff(phone);
CREATE INDEX IF NOT EXISTS idx_attendance_staff_date ON attendance(staff_id, date);
CREATE INDEX IF NOT EXISTS idx_inventory_merchant ON inventory(merchant_id);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_resolved ON stock_alerts(resolved);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);

-- ============================================================
-- ROW LEVEL SECURITY (single-tenant: anon + authenticated)
-- ============================================================
ALTER TABLE merchants ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_inventory_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cron_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

-- Policies for all tables (single-tenant: fully accessible)
DO $$ BEGIN
  DECLARE tbl text;
  BEGIN
    FOREACH tbl IN ARRAY ARRAY[
      'merchants','customers','service_cards','staff','attendance',
      'inventory','inventory_transactions','service_inventory_requirements',
      'stock_alerts','cron_logs','support_tickets'
    ] LOOP
      EXECUTE format('DROP POLICY IF EXISTS "anon_select_%s" ON %I', tbl, tbl);
      EXECUTE format('DROP POLICY IF EXISTS "anon_insert_%s" ON %I', tbl, tbl);
      EXECUTE format('DROP POLICY IF EXISTS "anon_update_%s" ON %I', tbl, tbl);
      EXECUTE format('DROP POLICY IF EXISTS "anon_delete_%s" ON %I', tbl, tbl);
      EXECUTE format('CREATE POLICY "anon_select_%s" ON %I FOR SELECT TO anon, authenticated USING (true)', tbl, tbl);
      EXECUTE format('CREATE POLICY "anon_insert_%s" ON %I FOR INSERT TO anon, authenticated WITH CHECK (true)', tbl, tbl);
      EXECUTE format('CREATE POLICY "anon_update_%s" ON %I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)', tbl, tbl);
      EXECUTE format('CREATE POLICY "anon_delete_%s" ON %I FOR DELETE TO anon, authenticated USING (true)', tbl, tbl);
    END LOOP;
  END;
END $$;

-- ============================================================
-- TRIGGER: Auto inventory deduction on job completion
-- ============================================================
CREATE OR REPLACE FUNCTION auto_deduct_inventory()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_qty integer;
  v_qty_per_1000L numeric;
  v_item_name text;
  v_inv_id uuid;
  v_merchant_id uuid;
  v_new_stock numeric;
  v_min_threshold numeric;
  v_deduct_qty numeric;
BEGIN
  IF NEW.job_status = 'completed' AND (OLD.job_status IS NULL OR OLD.job_status != 'completed') THEN
    IF NEW.quantity IS NOT NULL THEN
      v_qty := NEW.quantity;
    ELSE
      SELECT c.tank_capacity_liters INTO v_qty
        FROM customers c WHERE c.id = NEW.customer_id;
    END IF;

    SELECT c.merchant_id INTO v_merchant_id
      FROM customers c WHERE c.id = NEW.customer_id;

    FOR v_item_name, v_qty_per_1000L IN
      SELECT sir.item_name, sir.quantity_per_1000L
        FROM service_inventory_requirements sir
        WHERE sir.service_type = NEW.service_type
    LOOP
      SELECT i.id, i.current_stock, i.minimum_threshold
        INTO v_inv_id, v_new_stock, v_min_threshold
        FROM inventory i
        WHERE i.item_name = v_item_name AND i.merchant_id = v_merchant_id
        LIMIT 1;

      IF v_inv_id IS NOT NULL THEN
        v_deduct_qty := (v_qty::numeric / 1000.0) * v_qty_per_1000L;
        v_new_stock := v_new_stock - v_deduct_qty;

        UPDATE inventory
          SET current_stock = GREATEST(v_new_stock, 0)
          WHERE id = v_inv_id;

        INSERT INTO inventory_transactions (inventory_id, service_card_id, quantity_deducted)
          VALUES (v_inv_id, NEW.id, v_deduct_qty);

        IF v_new_stock < v_min_threshold THEN
          INSERT INTO stock_alerts (inventory_id, merchant_id, alert_type)
            VALUES (v_inv_id, v_merchant_id, 'low_stock');
        END IF;
      END IF;
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_auto_deduct_inventory ON service_cards;
CREATE TRIGGER trigger_auto_deduct_inventory
  AFTER UPDATE ON service_cards
  FOR EACH ROW
  EXECUTE FUNCTION auto_deduct_inventory();

-- ============================================================
-- SEED DATA
-- ============================================================
INSERT INTO merchants (id, business_name, owner_name, phone, email)
VALUES (
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  'AquaClean Services',
  'Sunil Sharma',
  '9876543210',
  'sunil@aquaclean.in'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO staff (id, merchant_id, name, phone, daily_wage_inr, is_active)
VALUES
  ('b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Ramesh Kumar', '9876543211', 500, true),
  ('b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Suresh Yadav', '9876543212', 550, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO customers (id, merchant_id, name, phone, address, latitude, longitude, tank_capacity_liters)
VALUES
  ('c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a31', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Priya Patel', '9876543213', '12 MG Road, Sector 5', 28.6139, 77.2090, 1000),
  ('c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a32', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Amit Verma', '9876543214', '45 Nehru Nagar', 28.6304, 77.2177, 2000),
  ('c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Neha Singh', '9876543215', '78 Civil Lines', 28.6865, 77.2215, 500)
ON CONFLICT (id) DO NOTHING;

INSERT INTO service_cards (id, customer_id, merchant_id, service_type, service_date, next_service_date, job_status, technician_id, notes)
VALUES
  ('d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a41', 'c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a31', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'standard_cleaning', current_date - 180, current_date, 'pending', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', '6-month cleaning due'),
  ('d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a42', 'c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a32', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'standard_cleaning', current_date - 5, current_date + 175, 'in_progress', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Large tank - extra chemicals needed'),
  ('d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a43', 'c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'standard_cleaning', current_date - 10, current_date + 170, 'completed', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', 'Small tank, routine cleaning'),
  ('d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', 'c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a31', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'sofa_cleaning', current_date - 3, current_date + 177, 'completed', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', '3-seater sofa set'),
  ('d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a45', 'c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a32', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'seats_cleaning', current_date - 1, current_date + 179, 'pending', NULL, 'Car interior - 5 seats')
ON CONFLICT (id) DO NOTHING;

INSERT INTO inventory (id, merchant_id, item_name, unit, current_stock, minimum_threshold)
VALUES
  ('e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a51', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Chlorine', 'g', 500.00, 50.00),
  ('e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a52', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Bleaching Powder', 'g', 2000.00, 200.00),
  ('e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a53', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Fabric Cleaner', 'ml', 5000.00, 500.00),
  ('e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a54', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Stain Remover', 'ml', 3000.00, 300.00),
  ('e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a55', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Upholstery Cleaner', 'ml', 4000.00, 400.00),
  ('e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a56', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Disinfectant Spray', 'ml', 2000.00, 200.00)
ON CONFLICT (id) DO NOTHING;

INSERT INTO service_inventory_requirements (service_type, item_name, quantity_per_1000L)
VALUES
  ('standard_cleaning', 'Chlorine', 30.00),
  ('standard_cleaning', 'Bleaching Powder', 100.00),
  ('sofa_cleaning', 'Fabric Cleaner', 250.00),
  ('sofa_cleaning', 'Stain Remover', 100.00),
  ('seats_cleaning', 'Upholstery Cleaner', 200.00),
  ('seats_cleaning', 'Disinfectant Spray', 50.00)
ON CONFLICT DO NOTHING;
